"""
compare_competency_v2_models.py

Read multiple `results/competency_v2_live_*` output directories produced by
`run_competency_v2_on_real_clusters.py --model X --output-dir Y` and render a
side-by-side comparison report.

Outputs:
    results/competency_v2_comparison/comparison.md     — markdown report
    results/competency_v2_comparison/comparison.csv    — flat per-run metrics
    results/competency_v2_comparison/titles_by_model.txt — full title list per model

Usage:
    python scripts/compare_competency_v2_models.py
        [--dirs results/competency_v2_live_*]
        [--output-dir results/competency_v2_comparison]
"""
from __future__ import annotations

import argparse
import csv
import json
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))


def _stat_dir(d: Path) -> dict | None:
    """Extract per-run summary stats from a competency_v2_live_* directory."""
    comp_p = d / "competencies.json"
    br_p = d / "batch_reasonings.json"
    if not comp_p.exists() or not br_p.exists():
        return None
    try:
        comps = json.loads(comp_p.read_text(encoding="utf-8"))
        brs = json.loads(br_p.read_text(encoding="utf-8"))
    except Exception as e:
        print(f"[WARN] failed to read {d}: {e}")
        return None

    if not comps and not brs:
        return None

    model = brs[0]["model"] if brs else "unknown"
    provider = brs[0]["provider"] if brs else "unknown"

    n_comp = len(comps)
    n_calls = len(brs)
    total_prompt = sum(br.get("prompt_tokens", 0) for br in brs)
    total_completion = sum(br.get("completion_tokens", 0) for br in brs)
    total_latency = sum(br.get("latency_seconds", 0.0) for br in brs)

    # Quality checks
    all_text = " ".join(
        (c.get("description") or "") + " " + (c.get("rationale") or "") + " " + (c.get("title") or "")
        for c in comps
    )
    br_raw = " ".join((br.get("raw_response") or "") for br in brs)

    n_religious = (all_text.lower() + " " + br_raw.lower()).count("religious")
    n_and_raw = br_raw.lower().count(" and ")  # 0 = catastrophic token bug

    grounding_scores = [float(c.get("grounding_score_preview", 0.0)) for c in comps]
    mean_grounding = sum(grounding_scores) / max(1, len(grounding_scores))
    pct_perfect_grounding = (
        sum(1 for g in grounding_scores if g >= 0.999) / max(1, len(grounding_scores))
    ) * 100.0

    rationale_lens = [len(c.get("rationale", "")) for c in comps]
    mean_rationale = sum(rationale_lens) / max(1, len(rationale_lens))

    skills_per_comp = [len(c.get("related_skills", [])) for c in comps]
    mean_skills = sum(skills_per_comp) / max(1, len(skills_per_comp))

    # Per-cluster coverage (which clusters produced competencies)
    cluster_ids = {c.get("cluster_id", "") for c in comps if c.get("cluster_id")}

    titles = [c.get("title", "") for c in comps]

    return {
        "dir": str(d),
        "model": model,
        "provider": provider,
        "n_competencies": n_comp,
        "n_llm_calls": n_calls,
        "prompt_tokens": total_prompt,
        "completion_tokens": total_completion,
        "total_tokens": total_prompt + total_completion,
        "latency_seconds": total_latency,
        "mean_latency_per_call": total_latency / max(1, n_calls),
        "religious_bug_count": n_religious,
        "and_count_raw": n_and_raw,
        "mean_grounding": mean_grounding,
        "pct_perfect_grounding": pct_perfect_grounding,
        "mean_rationale_chars": mean_rationale,
        "mean_skills_per_comp": mean_skills,
        "clusters_covered": sorted(cluster_ids),
        "n_clusters_covered": len(cluster_ids),
        "titles": titles,
    }


def _render_markdown(stats: list) -> str:
    lines = []
    lines.append("# Phase 2.2 — Competency Generator Model A/B Comparison")
    lines.append("")
    lines.append(
        "Per-run metrics across the same 10 hard+knowledge clusters from "
        "`results.old2/`. Generated by `scripts/compare_competency_v2_models.py`."
    )
    lines.append("")

    # Summary table
    lines.append("## Side-by-side summary")
    lines.append("")
    lines.append(
        "| Model | Provider | Competencies | Clusters covered | Mean grounding | % perfect grounding | Mean rationale | Mean skills/comp | Total latency | Tokens (in/out) | `religious` bug |"
    )
    lines.append(
        "|---|---|---|---|---|---|---|---|---|---|---|"
    )
    for s in stats:
        bug_marker = (
            "**BROKEN**" if s["and_count_raw"] == 0 else
            (f"**{s['religious_bug_count']}**" if s["religious_bug_count"] > 0 else "0")
        )
        lines.append(
            f"| `{s['model']}` | {s['provider']} | {s['n_competencies']} | "
            f"{s['n_clusters_covered']}/10 | {s['mean_grounding']:.3f} | "
            f"{s['pct_perfect_grounding']:.0f}% | {s['mean_rationale_chars']:.0f}c | "
            f"{s['mean_skills_per_comp']:.1f} | {s['latency_seconds']:.0f}s | "
            f"{s['prompt_tokens']:,}/{s['completion_tokens']:,} | {bug_marker} |"
        )
    lines.append("")

    # Bug-check detail
    lines.append("## Token-corruption bug check")
    lines.append("")
    lines.append("`\" and \" count = 0` is impossible for English text and indicates a token-level corruption in the model output. Confirmed for DeepSeek-V3.2 on 2026-05-12.")
    lines.append("")
    lines.append("| Model | `\"religious\"` occurrences | `\" and \"` count | Verdict |")
    lines.append("|---|---|---|---|")
    for s in stats:
        verdict = "🚨 BROKEN" if s["and_count_raw"] == 0 else (
            "⚠ has 'religious' in output" if s["religious_bug_count"] > 0 else "✅ clean"
        )
        lines.append(
            f"| `{s['model']}` | {s['religious_bug_count']} | {s['and_count_raw']} | {verdict} |"
        )
    lines.append("")

    # Cluster coverage
    lines.append("## Cluster coverage")
    lines.append("")
    lines.append("Which clusters successfully produced ≥1 competency per model. Cells = number of competencies that cluster produced (post-validation, post-dedup).")
    lines.append("")

    # Build the cluster set across all models
    all_clusters = sorted({c for s in stats for c in s["clusters_covered"]})

    header = "| Cluster | " + " | ".join(f"`{s['model']}`" for s in stats) + " |"
    sep = "|---|" + "---|" * len(stats)
    lines.append(header)
    lines.append(sep)
    for cid in all_clusters:
        row = [f"`{cid}`"]
        for s in stats:
            # count titles whose cluster_id matches
            # We saved cluster_ids as a set; need per-cluster count from competencies.json
            # Re-read to count
            comp_p = Path(s["dir"]) / "competencies.json"
            comps = json.loads(comp_p.read_text(encoding="utf-8"))
            n = sum(1 for c in comps if c.get("cluster_id") == cid)
            row.append(str(n) if n else "—")
        lines.append("| " + " | ".join(row) + " |")
    lines.append("")

    # Titles by model
    lines.append("## Titles produced — full list")
    lines.append("")
    for s in stats:
        lines.append(f"### `{s['model']}` ({s['n_competencies']} competencies)")
        if not s["titles"]:
            lines.append("_no competencies survived validation/dedup_")
        else:
            for i, t in enumerate(s["titles"], 1):
                lines.append(f"{i}. {t}")
        lines.append("")

    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--dirs",
        nargs="*",
        default=None,
        help="Specific output dirs to compare (default: auto-discover results/competency_v2_live_*)",
    )
    parser.add_argument("--output-dir", default="results/competency_v2_comparison")
    args = parser.parse_args()

    if args.dirs:
        dirs = [Path(d) for d in args.dirs]
    else:
        dirs = sorted((PROJECT_ROOT / "results").glob("competency_v2_live_*"))
        # Also include the original (un-suffixed) run if present
        original = PROJECT_ROOT / "results" / "competency_v2_live"
        if original.exists():
            dirs = [original] + [d for d in dirs if d != original]

    if not dirs:
        print("[ERROR] no input directories found")
        return 1

    out_dir = Path(args.output_dir)
    if not out_dir.is_absolute():
        out_dir = PROJECT_ROOT / out_dir
    out_dir.mkdir(parents=True, exist_ok=True)

    print(f"[INFO] reading from {len(dirs)} directories:")
    for d in dirs:
        print(f"   {d}")
    print()

    stats = []
    for d in dirs:
        s = _stat_dir(d)
        if s is not None:
            stats.append(s)

    if not stats:
        print("[ERROR] no readable runs")
        return 1

    # Order: cheapest by provider+latency for stable reading
    stats.sort(key=lambda s: (s["provider"], s["mean_latency_per_call"]))

    # CSV
    csv_path = out_dir / "comparison.csv"
    with open(csv_path, "w", encoding="utf-8", newline="") as f:
        cols = [
            "model", "provider", "n_competencies", "n_llm_calls",
            "prompt_tokens", "completion_tokens", "total_tokens",
            "latency_seconds", "mean_latency_per_call",
            "religious_bug_count", "and_count_raw",
            "mean_grounding", "pct_perfect_grounding",
            "mean_rationale_chars", "mean_skills_per_comp",
            "n_clusters_covered",
        ]
        w = csv.DictWriter(f, fieldnames=cols, extrasaction="ignore")
        w.writeheader()
        for s in stats:
            w.writerow(s)
    print(f"[INFO] wrote {csv_path}")

    # Markdown
    md_path = out_dir / "comparison.md"
    md_path.write_text(_render_markdown(stats), encoding="utf-8")
    print(f"[INFO] wrote {md_path}")

    # Plain titles dump
    titles_path = out_dir / "titles_by_model.txt"
    with open(titles_path, "w", encoding="utf-8") as f:
        for s in stats:
            f.write(f"=== {s['model']} ({s['n_competencies']} competencies) ===\n")
            for i, t in enumerate(s["titles"], 1):
                f.write(f"  {i}. {t}\n")
            f.write("\n")
    print(f"[INFO] wrote {titles_path}")

    # Print a quick console summary too
    print()
    print("=" * 100)
    print(f"{'Model':<35s} {'comp':>5s} {'cov':>4s} {'grnd':>6s} {'rat_c':>6s} {'skl':>5s} {'lat':>6s} {'bug':>6s}")
    print("=" * 100)
    for s in stats:
        bug = "BROKEN" if s["and_count_raw"] == 0 else (str(s["religious_bug_count"]) if s["religious_bug_count"] else "OK")
        print(
            f"{s['model']:<35s} {s['n_competencies']:>5d} {s['n_clusters_covered']:>2d}/10 "
            f"{s['mean_grounding']:>6.3f} {s['mean_rationale_chars']:>6.0f} "
            f"{s['mean_skills_per_comp']:>5.1f} {s['latency_seconds']:>5.0f}s {bug:>6s}"
        )
    print()

    return 0


if __name__ == "__main__":
    sys.exit(main())
